# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1

    working_directory: ~/repo
    branches:
      only:
        - dev

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install dependencies and module
          command: |
            python3 -m venv venv
            . venv/bin/activate
            sudo apt install sysstat
            pip install -r requirements.txt
            pip install -e .

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            pytest . --cov=permon

      - run:
          name: Lint
          command: |
            . venv/bin/activate
            flake8 .
      
      - run:
          name: Upload Coverage
          command: |
            bash <(curl -s https://codecov.io/bash)

      # - store_artifacts:
      #     path: test-reports
      #     destination: test-reports